/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CppLibrary */

#ifndef _Included_CppLibrary
#define _Included_CppLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CppLibrary
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CppLibrary_hello
  (JNIEnv *, jobject);

/*
 * Class:     CppLibrary
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CppLibrary_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CppLibrary
 * Method:    diff
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CppLibrary_diff
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
